context:
  version: "1.80.0"

package:
  name: grpc-bazel-rules
  version: ${{ version }}

source:
  url: https://github.com/grpc/grpc/archive/v${{ version }}.tar.gz
  sha256: 38f58596277fa632064cc0719b9ece4381c8c77461cb51e9b66ca149574b7865
  patches:
    - 0001-Adjust-to-support-xla-specific-features.patch

build:
  number: 0
  noarch: generic

requirements:
  run_constraints:
    - libgrpc ${{ version }}.*

tests:
  - package_contents:
      files:
        - share/bazel/grpc/bazel/python_rules.bzl

about:
  homepage: https://grpc.io/
  repository: https://github.com/grpc/grpc
  license: Apache-2.0
  license_file: LICENSE
  summary: Bazel rules for grpc

extra:
  recipe-maintainers:
    - conda-forge/grpc-cpp
